training_params:
  epochs: 100
  batch_size: 64              
  optimizer:
    name: "Adam"
    learning_rate: 0.001
    weight_decay: 0.001       
  loss_function:
    use_pos_weight: False     
  scheduler:
    name: "ReduceLROnPlateau"
    patience: 5
    factor: 0.5
  early_stopping:
    patience: 15              
    delta: 0.001