dataset_info:
  split_ratio: 0.2
  features:
    columns:
      [
        State,
        Accountlength,
        Area_code,
        International_plan,
        Voice_mail_plan,
        Number_vmail_messages,
        Total_day_minutes,
        Total_day_calls,
        Total_day_charge,
        Total_eve_minutes,
        Total_eve_calls,
        Total_eve_charge,
        Total_night_minutes,
        Total_night_calls,
        Total_night_charge,
        Total_intl_minutes,
        Total_intl_calls,
        Total_intl_charge,
        Customer_service_calls
      ]
    num_columns:
      [
        #State
        Accountlength,
        #Area_code, 
        Number_vmail_messages,
        Total_day_minutes,
        Total_day_calls,
        Total_day_charge,
        Total_eve_minutes,
        Total_eve_calls,
        Total_eve_charge,
        Total_night_minutes,
        Total_night_calls,
        Total_night_charge,
        Total_intl_minutes,
        Total_intl_calls,
        Total_intl_charge,
        Customer_service_calls
      ]
    binary_columns: [International_plan, Voice_mail_plan]
    cat_columns: ["<empty>"]
    target: Churn

data_source:
  dataset_name: teleco-churn-customers
  data_path:
    dataset_path: "../../datasets/telecom_churn100.csv"
    preprocessor_filename: teleco-churn_preprocessor.joblib
